// web/components/pokemonCard.vue
<template>
  <div
    class="inline-block max-w-xs bg-white bg-opacity-10 rounded-3xl relative"
  >
    <div class="py-2">
      <h1 class="text-white text-center text-4xl font-bold">{{ name }}</h1>
      <h2 class="text-white text-center">{{ primaryType }}</h2>
    </div>

    <div class="bg-white bg-opacity-10 rounded-3xl p-8 h-80">
      <img :src="image" alt="pokemon" />
    </div>

    <p
      class="text-white text-2xl font-bold absolute bottom-0 right-0 pr-4 pb-4"
    >
      {{ pokedexNumber }}
    </p>
  </div>
</template>

<script>
export default {
  props: {
    name: {
      type: String,
      required: true,
    },
    primaryType: {
      type: String,
      required: true,
    },
    pokedexNumber: {
      type: Number,
      required: true,
    },
    image: {
      type: String,
      required: true,
    },
  },
}
</script>

// web/src/components/PokemonCard/index.tsx
import React from 'react';

import PokemonData from '../../dtos/PokemonData';

interface PokemonCardProps {
    onClick(): void;
    pokemonData: PokemonData;
}

const PokemonCard: React.FC<PokemonCardProps> = ({ 
    onClick,
    pokemonData
}) => {
    const handleClickOnPokemonCard = () => {
        onClick();
    }

    return (
        <div className="pokemon-card"
            onClick={() => handleClickOnPokemonCard()}
        >
            <img
                className="h-32 md:h-32 xl:h-40 m-auto"
                src={pokemonData.sprite_url} 
                alt="Pokemon"
            />

            <label className="text-center block md:mt-2 font-semibold">
                {pokemonData.name}
            </label>
        </div>
    );
};

export default PokemonCard;
