// Projeto Pokemon RedFox/Front end - angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Pokedex';
}

<!-- MENU NAV BAR -->
<!-- MENU NAV BAR -->
<!-- MENU NAV BAR -->
<nav class="navbar" role="navigation" aria-label="main navigation" id="menu">
    <div class="navbar-brand">
      <a class="navbar-item" routerLink="/">
        <img src="../assets/logoPoke.png" width="112" height="28">
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" routerLink="/">
          Home
        </a>
  
        <a class="navbar-item" routerLink="/cadPokemon">
          Cadastrar Pokemon
        </a>
  
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>
  
          <div class="navbar-dropdown">
            <a class="navbar-item" href="https://www.facebook.com/igor.nascimento.50364">
              Facebook
            </a>
            <a class="navbar-item" href="https://www.linkedin.com/in/igor-nascimento-50230a188/">
              Linkedin
            </a>
            <a class="navbar-item" href="https://www.github.com/irgor">
              GitHub
            </a>
          </div>
        </div>
      </div>
  
    </div>
  </nav>

<!-- MENU NAV BAR -->
<!-- MENU NAV BAR -->
<!-- MENU NAV BAR -->

<router-outlet></router-outlet>

// frontend/src/App.vue

<template>



  <div class="corpo">

    <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://i.pinimg.com/originals/a9/4f/4d/a94f4d75a2e429a20838d28d2ae2b996.png" width="89" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" >
        <router-link to="/">Home</router-link>
        
      </a>

      <a class="navbar-item" href="/createpokemon">
          <router-link to="/createpokemon">Criar Pokemon</router-link>
      </a>

    </div>

  </div>
</nav>
   
    <router-view></router-view>

  </div>

</template>

<script>


export default {

   
}
</script>

<style>
    .corpo {
      font-family: Helvetica, sans-serif;
      width: 96%;
      margin: 0 auto;
    }

</style>
